
package soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetActorsInfoService", targetNamespace = "http://soap/", wsdlLocation = "http://localhost:8080/projeto2_WebService/GetActorsInfo?wsdl")
public class GetActorsInfoService
    extends Service
{

    private final static URL GETACTORSINFOSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETACTORSINFOSERVICE_EXCEPTION;
    private final static QName GETACTORSINFOSERVICE_QNAME = new QName("http://soap/", "GetActorsInfoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/projeto2_WebService/GetActorsInfo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETACTORSINFOSERVICE_WSDL_LOCATION = url;
        GETACTORSINFOSERVICE_EXCEPTION = e;
    }

    public GetActorsInfoService() {
        super(__getWsdlLocation(), GETACTORSINFOSERVICE_QNAME);
    }

    public GetActorsInfoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETACTORSINFOSERVICE_QNAME, features);
    }

    public GetActorsInfoService(URL wsdlLocation) {
        super(wsdlLocation, GETACTORSINFOSERVICE_QNAME);
    }

    public GetActorsInfoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETACTORSINFOSERVICE_QNAME, features);
    }

    public GetActorsInfoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetActorsInfoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetActorsInfo
     */
    @WebEndpoint(name = "GetActorsInfoPort")
    public GetActorsInfo getGetActorsInfoPort() {
        return super.getPort(new QName("http://soap/", "GetActorsInfoPort"), GetActorsInfo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetActorsInfo
     */
    @WebEndpoint(name = "GetActorsInfoPort")
    public GetActorsInfo getGetActorsInfoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap/", "GetActorsInfoPort"), GetActorsInfo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETACTORSINFOSERVICE_EXCEPTION!= null) {
            throw GETACTORSINFOSERVICE_EXCEPTION;
        }
        return GETACTORSINFOSERVICE_WSDL_LOCATION;
    }

}
