
package soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GetActorsInfo", targetNamespace = "http://soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetActorsInfo {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<soap.ActorJPAProcessed>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actorsProcessing", targetNamespace = "http://soap/", className = "soap.ActorsProcessing")
    @ResponseWrapper(localName = "actorsProcessingResponse", targetNamespace = "http://soap/", className = "soap.ActorsProcessingResponse")
    public List<ActorJPAProcessed> actorsProcessing(
        @WebParam(name = "arg0", targetNamespace = "")
        List<ActorJPA> arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<soap.ActorJPAProcessed>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getActorByMovieTitle", targetNamespace = "http://soap/", className = "soap.GetActorByMovieTitle")
    @ResponseWrapper(localName = "getActorByMovieTitleResponse", targetNamespace = "http://soap/", className = "soap.GetActorByMovieTitleResponse")
    public List<ActorJPAProcessed> getActorByMovieTitle(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<soap.ActorJPAProcessed>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getActors", targetNamespace = "http://soap/", className = "soap.GetActors")
    @ResponseWrapper(localName = "getActorsResponse", targetNamespace = "http://soap/", className = "soap.GetActorsResponse")
    public List<ActorJPAProcessed> getActors();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "setProperties", targetNamespace = "http://soap/", className = "soap.SetProperties")
    @ResponseWrapper(localName = "setPropertiesResponse", targetNamespace = "http://soap/", className = "soap.SetPropertiesResponse")
    public void setProperties();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<soap.ActorJPAProcessed>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getActorByName", targetNamespace = "http://soap/", className = "soap.GetActorByName")
    @ResponseWrapper(localName = "getActorByNameResponse", targetNamespace = "http://soap/", className = "soap.GetActorByNameResponse")
    public List<ActorJPAProcessed> getActorByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
